INSERT INTO GRADE_TYPE_WEIGHT (SECTION_ID, GRADE_TYPE_CODE, NUMBER_PER_SECTION, PERCENT_OF_FINAL_GRADE, DROP_LOWEST, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE)
VALUES
    (1, 'A', 5, 30.00, 'N', 'Admin', SYSDATE, 'Admin', SYSDATE),
    (2, 'B', 4, 25.00, 'N', 'Admin', SYSDATE, 'Admin', SYSDATE),
    (3, 'C', 3, 20.00, 'N', 'Admin', SYSDATE, 'Admin', SYSDATE),
    (4, 'D', 2, 15.00, 'N', 'Admin', SYSDATE, 'Admin', SYSDATE),
    (5, 'F', 1, 10.00, 'N', 'Admin', SYSDATE, 'Admin', SYSDATE);