CREATE TABLE COURSE (
    COURSE_NO VARCHAR2(8 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(50 CHAR),
    COST NUMBER(8, 2),
    PREREQUISITE VARCHAR2(8 CHAR),
    CREATED_BY VARCHAR2(30 CHAR) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    MODIFIED_BY VARCHAR2(30 CHAR) NOT NULL,
    MODIFIED_DATE DATE NOT NULL,
    
    CONSTRAINT PK_COURSE PRIMARY KEY (COURSE_NO)
);